spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_gpt
    username: springuser
    password: spring123
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: update
