package com.example.spring_gpt.mask;

import com.example.spring_gpt.message.ChatMessage;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@CrossOrigin
@Controller // This means that this class is a Controller
@RequestMapping(path="/mask") // This means URL's start with /mask (after Application path)
public class MaskController {
    @Autowired // This means to get the bean called maskRepository
    // Which is auto-generated by Spring, we will use it to handle the data
    private MaskRepository maskRepository;

    @PostMapping(path="/add_all") // Map ONLY POST Requests
    public @ResponseBody String addAllMasks (@RequestBody List<Mask> maskList) {
        // @ResponseBody means the returned String is the response, not a view name
        // @RequestParam means it is a parameter from the GET or POST request
        for (Mask mask : maskList) {
            for (ChatMessage chatMessage : mask.getContext()) {
                chatMessage.setMask(mask);
            }
        }
        maskRepository.saveAll(maskList);
        return "Saved";
    }

    @GetMapping(path="/all")
    public @ResponseBody Iterable<Mask> getAllMasks() {
        // This returns a JSON or XML with the users
        return maskRepository.findAll();
    }
}